### ISSUE TITLE
Publish crates

### ISSUE THREAD

**Issue by doitian** [EthanYuan/open-transaction-pool#13]
- Use uniform prefix for all crates
- Ensure there's no conflict
- Refer to the [script](https://github.com/nervosnetwork/ckb/blob/develop/devtools/release/publish-crates.sh) to publish crates in ckb

**Comment by EthanYuan** [comment]
- https://github.com/EthanYuan/open-transaction-pool/pull/16

**Comment by EthanYuan** [comment]
publish crates:

https://crates.io/crates/otx-format
https://crates.io/crates/otx-pool
https://crates.io/crates/otx-pool-config
https://crates.io/crates/otx-pool-plugin-atomic-swap
https://crates.io/crates/otx-pool-plugin-dust-collector
https://crates.io/crates/otx-pool-plugin-signer
https://crates.io/crates/otx-sdk
https://crates.io/crates/otx-pool-plugin-protocol
https://crates.io/crates/open-transaction-pool
