### ISSUE TITLE
Let JSONRPC serializes Open Transaction into JSON

### ISSUE THREAD

**Issue by doitian** [EthanYuan/open-transaction-pool#7]
It's easy for inspecting and debugging.

**Comment by EthanYuan** [comment]
Before making changes, you can try to use [dump_data](https://github.com/EthanYuan/open-transaction-pool/blob/1668d2bdcffdc78546f840bbbf57b26ed82687c5/integration-test/src/utils/instruction/ckb.rs#L59).

Here is a case：

https://github.com/EthanYuan/open-transaction-pool/blob/12eda77e2ff94ad157896ecc53344ea417a458a5/integration-test/src/tests/swap/atomic_swap.rs#L317

@doitian

**Comment by doitian** [comment]
Better add a executable or RPC to translate between molecule and JSON.

**Comment by EthanYuan** [comment]
- https://github.com/EthanYuan/open-transaction-pool/pull/10
https://github.com/EthanYuan/open-transaction-pool/pull/10/commits/b6dbc039f9898c9e40e2d00a1dbd58664356d722
